export const styles = {
  image: {
    width: "100%",
    height: "763px",
  },
  contentContainer: {
    background: "linear-gradient(to right, #4DCA79, #1CBDDD)",
    width: "80%",
    maxWidth: "630px",
    height: "306px",
    top: "56%",
    left: "5%",
    padding: "40px 40px 40px 40px",
    gap: "20px",
    position: "absolute",
  },
  heading: {
    fontFamily: "Inter",
    fontSize: "48px",
    fontWeight: 700,
    lineHeight: "48px",
    letterSpacing: "-0.02em",
    textAlign: "left",
  },
  consultationbutton: {
    width: "214px",
    height: "38px",
    padding: "12px 20px",
    borderRadius: "4px",
    fontSize: "14px",
    gap: "8px",
  },
  learnMoreButton: {
    width: "129px",
    height: "38px",
    borderRadius: "4px",
    fontSize: "14px",
    gap: "8px",
  },
};
